#define TRIG_PIN 13
#define ECHO_PIN 12
#define BLUE_LED 11
#define RED_LED 10
#define M_RIGHT_SPEED 3
#define M_RIGHT_DIR 2
#define M_LEFT_SPEED 5
#define M_LEFT_DIR 4
#define LOW_SPEED 125
#define MID_SPEED 200
#define HIGH_SPEED 255
#define MOVE_FRONT true
#define MOVE_BACK false
